// VEHICLE_IMG Page
export const VEHICLE_IMG_FETCHING = "VEHICLE_IMG_FETCHING";
export const VEHICLE_IMG_SUCCESS = "VEHICLE_IMG_SUCCESS";
export const VEHICLE_IMG_FAILED = "VEHICLE_IMG_FAILED";
// DRIVER_ID Page
export const DRIVER_ID_FETCHING = "DRIVER_ID_FETCHING";
export const DRIVER_ID_SUCCESS = "DRIVER_ID_SUCCESS";
export const DRIVER_ID_FAILED = "DRIVER_ID_FAILED";

// FINANCIAL_IMG Page

export const FINANCIAL_IMG_FETCHING = "FINANCIAL_IMG_FETCHING";
export const FINANCIAL_IMG_SUCCESS = "FINANCIAL_IMG_SUCCESS";
export const FINANCIAL_IMG_FAILED = "FINANCIAL_IMG_FAILED";

// INSURANCE_IMG Page
export const INSURANCE_IMG_FETCHING = "INSURANCE_IMG_FETCHING";
export const INSURANCE_IMG_SUCCESS = "INSURANCE_IMG_SUCCESS";
export const INSURANCE_IMG_FAILED = "INSURANCE_IMG_FAILED";

// OILCARD_IMG Page
export const OILCARD_IMG_FETCHING = "OILCARD_IMG_FETCHING";
export const OILCARD_IMG_SUCCESS = "OILCARD_IMG_SUCCESS";
export const OILCARD_IMG_FAILED = "OILCARD_IMG_FAILED";

// VEHICLE_STEP Page
export const VEHICLE_STEP_FETCHING = "VEHICLE_STEP_FETCHING";
export const VEHICLE_STEP_SUCCESS = "VEHICLE_STEP_SUCCESS";
export const VEHICLE_STEP_FAILED = "VEHICLE_STEP_FAILED";

//// SET IMG ALL
export const FETCHING = "FETCHING";
export const SETBASE64_CAR = "SETBASE64_CAR";
export const SETBASE64_BUY = "SETBASE64_BUY";
export const SETBASE64_SALE = "SETBASE64_SALE";
